# Generated by Django 4.2.7 on 2023-12-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_image_alter_book_borrowing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/media/uploads/'),
        ),
    ]
